### ISSUE TITLE
Sometimes the game doesn't start and closes automatically

### ISSUE THREAD

**Issue by andreimesquita** [marciovmf/ldk#41]
The problem: The screen goes black and the game closes automatically.

Workaround: To solve this issue, I need to execute `nmake clean` and `nmake game` like three times consecutively, so the game initializes without problems.
I'll try to film when It happens again.

**Comment by marciovmf** [comment]
This was the game writting past the pre-allocated memory. This pre-allocation system will change anyways to prevent this kind of mistake. Tanks for reporting.
